// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4hSunmogNRsFGWI0xM6cP3HBeNA6wTQs',
    appId: '1:722793713539:web:3b72b0d19326345ddfb0b6',
    messagingSenderId: '722793713539',
    projectId: 'taskminder-app',
    authDomain: 'taskminder-app.firebaseapp.com',
    databaseURL: 'https://taskminder-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskminder-app.appspot.com',
    measurementId: 'G-BRQJ9610QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChi5NXPOA5povAjOYtOr0LHgxcai03ORM',
    appId: '1:722793713539:android:62840035a0725777dfb0b6',
    messagingSenderId: '722793713539',
    projectId: 'taskminder-app',
    databaseURL: 'https://taskminder-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskminder-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5d74XA4V8jLfaYwiZCq8qCCdi_TVgl8',
    appId: '1:722793713539:ios:5cb39f026e9b5740dfb0b6',
    messagingSenderId: '722793713539',
    projectId: 'taskminder-app',
    databaseURL: 'https://taskminder-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskminder-app.appspot.com',
    iosClientId: '722793713539-le680mqr00pigsdm6u9ltq9o5agf27qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5d74XA4V8jLfaYwiZCq8qCCdi_TVgl8',
    appId: '1:722793713539:ios:5cb39f026e9b5740dfb0b6',
    messagingSenderId: '722793713539',
    projectId: 'taskminder-app',
    databaseURL: 'https://taskminder-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskminder-app.appspot.com',
    iosClientId: '722793713539-le680mqr00pigsdm6u9ltq9o5agf27qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4hSunmogNRsFGWI0xM6cP3HBeNA6wTQs',
    appId: '1:722793713539:web:12d86c20a6ffd660dfb0b6',
    messagingSenderId: '722793713539',
    projectId: 'taskminder-app',
    authDomain: 'taskminder-app.firebaseapp.com',
    databaseURL: 'https://taskminder-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskminder-app.appspot.com',
    measurementId: 'G-X5WGVYGGC4',
  );

}