// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzDTbUMa_jDY1drv9DTMPx57kbtLrNhM',
    appId: '1:446277723082:web:650ca0a834c55e4e286533',
    messagingSenderId: '446277723082',
    projectId: 'taskminder-final',
    authDomain: 'taskminder-final.firebaseapp.com',
    storageBucket: 'taskminder-final.appspot.com',
    measurementId: 'G-9853F2DJQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCns4gxZncJ9uyWCGkCPCcUBi16_2pDmnw',
    appId: '1:446277723082:android:9a6972c2eee7f2e9286533',
    messagingSenderId: '446277723082',
    projectId: 'taskminder-final',
    storageBucket: 'taskminder-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTOqD2oMCmvsEOeVQI-rnjBW9S3RQlTQ',
    appId: '1:446277723082:ios:bcf34f60383958ed286533',
    messagingSenderId: '446277723082',
    projectId: 'taskminder-final',
    storageBucket: 'taskminder-final.appspot.com',
    iosClientId: '446277723082-hva6n7c5cvhjqb3q3nlumfacrjen10nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTOqD2oMCmvsEOeVQI-rnjBW9S3RQlTQ',
    appId: '1:446277723082:ios:bcf34f60383958ed286533',
    messagingSenderId: '446277723082',
    projectId: 'taskminder-final',
    storageBucket: 'taskminder-final.appspot.com',
    iosClientId: '446277723082-hva6n7c5cvhjqb3q3nlumfacrjen10nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuzDTbUMa_jDY1drv9DTMPx57kbtLrNhM',
    appId: '1:446277723082:web:e47e3cdecb943363286533',
    messagingSenderId: '446277723082',
    projectId: 'taskminder-final',
    authDomain: 'taskminder-final.firebaseapp.com',
    storageBucket: 'taskminder-final.appspot.com',
    measurementId: 'G-42J5N3F2BQ',
  );

}